# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!
workspace 'FlutterExample'

flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterExample' do
end

target 'FlutterWrapper' do
  project '../FlutterWrapper/FlutterWrapper.xcodeproj'
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
